#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Samba 4 AD Manager — Installation Script
#
# Installs and configures:
#   1. Samba 4 AD DC packages (samba-ad-dc)
#   2. Python dependencies (FastAPI, ldap3, psutil, etc.)
#   3. systemd service for the web management app
#
# After installation, open http://<server-ip>:8000 in a browser
# to run the Setup Wizard and provision your AD domain.
#
# Usage:
#   sudo ./install.sh [--domain CORP.LOCAL] [--admin-pass 'Passw0rd!']
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
info "Samba 4 AD Manager — Installation Starting..."

# Must be root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (use sudo)."
fi

# Must be Linux
if [[ "$(uname -s)" != "Linux" ]]; then
    error "This script only runs on Linux."
fi

# Detect distribution
PKG_MANAGER=""
if command -v apt-get &>/dev/null; then
    PKG_MANAGER="apt"
elif command -v dnf &>/dev/null; then
    PKG_MANAGER="dnf"
elif command -v yum &>/dev/null; then
    PKG_MANAGER="yum"
else
    error "Unsupported distribution. Only apt/dnf/yum are supported."
fi

info "Detected package manager: $PKG_MANAGER"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="${SCRIPT_DIR}"
SERVICE_USER="samba-adm"
VENV_DIR="${APP_DIR}/backend/.venv"

# ---------------------------------------------------------------------------
# Step 1: Install Samba AD DC packages
# ---------------------------------------------------------------------------
info "Installing Samba 4 AD DC packages..."

case "$PKG_MANAGER" in
    apt)
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y -qq samba smbclient winbind ldap-utils \
            python3 python3-venv python3-pip 2>/dev/null
        # Disable default smbd/nmbd to avoid conflict with samba-ad-dc
        systemctl stop smbd nmbd winbind 2>/dev/null || true
        systemctl disable smbd nmbd winbind 2>/dev/null || true
        ;;
    dnf|yum)
        $PKG_MANAGER install -y -q samba samba-client samba-winbind \
            openldap-clients python3 python3-pip 2>/dev/null
        ;;
esac

# Verify samba-tool is available
if ! command -v samba-tool &>/dev/null; then
    error "samba-tool not found after installation. Please install samba-ad-dc manually."
fi
ok "Samba packages installed: $(samba --version 2>/dev/null | head -1)"

# ---------------------------------------------------------------------------
# Step 2: Create service user
# ---------------------------------------------------------------------------
info "Setting up service user: $SERVICE_USER"

if ! id "$SERVICE_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
    ok "Created system user: $SERVICE_USER"
else
    info "User $SERVICE_USER already exists."
fi

# ---------------------------------------------------------------------------
# Step 3: Set up Python virtual environment
# ---------------------------------------------------------------------------
info "Setting up Python virtual environment..."

if [[ ! -d "$VENV_DIR" ]]; then
    python3 -m venv "$VENV_DIR"
    ok "Created virtual environment at $VENV_DIR"
fi

# Install Python dependencies
info "Installing Python dependencies..."
"$VENV_DIR/bin/pip" install --upgrade pip -q
"$VENV_DIR/bin/pip" install -e "$APP_DIR/backend/" -q
"$VENV_DIR/bin/pip" install pyjwt python-multipart httpx pytest pytest-cov -q
ok "Python dependencies installed"

# ---------------------------------------------------------------------------
# Step 4: Create .env file (if not exists)
# ---------------------------------------------------------------------------
ENV_FILE="${APP_DIR}/.env"

if [[ ! -f "$ENV_FILE" ]]; then
    info "Creating .env configuration file..."

    # Get server IP
    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "127.0.0.1")

    cat > "$ENV_FILE" << EOF
# Samba 4 AD Manager — Configuration
# Generated by install.sh on $(date)

# Runtime mode: mock (no Samba) or ldap (real Samba DC)
APP_MODE=ldap

# LDAP connection
LDAP_HOST=127.0.0.1
LDAP_PORT=389
LDAP_USE_SSL=false
LDAP_BIND_DN=CN=Administrator,CN=Users,DC=CORP,DC=LOCAL
LDAP_BIND_PASSWORD=ChangeMe123!
LDAP_SEARCH_BASE=DC=CORP,DC=LOCAL

# Samba tool
SAMBA_TOOL_PATH=samba-tool
SAMBA_CONFIG=/etc/samba/smb.conf

# App settings
APP_NAME=Samba 4 AD Manager
APP_VERSION=0.1.0
DEBUG=false
EOF

    ok "Created .env at $ENV_FILE"
    warn "Edit $ENV_FILE to match your domain after provisioning."
else
    info ".env already exists, skipping."
fi

# ---------------------------------------------------------------------------
# Step 5: Create systemd service
# ---------------------------------------------------------------------------
SERVICE_FILE="/etc/systemd/system/samba-ad-manager.service"

info "Creating systemd service..."

cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Samba 4 AD Manager — Web Management Portal
After=network.target samba-ad-dc.service
Wants=network.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$APP_DIR/backend
EnvironmentFile=$APP_DIR/.env
ExecStart=$VENV_DIR/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000
Restart=always
RestartSec=5

# Security hardening
NoNewPrivileges=yes
ProtectSystem=full
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths=$APP_DIR /etc/samba /var/lib/samba /var/cache/samba /var/run/samba

[Install]
WantedBy=multi-user.target
EOF

# Set ownership
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIR"

systemctl daemon-reload
systemctl enable samba-ad-manager
ok "systemd service created and enabled: samba-ad-manager"

# ---------------------------------------------------------------------------
# Step 6: Optional — auto-provision domain
# ---------------------------------------------------------------------------
DOMAIN=""
ADMIN_PASS=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"; shift 2 ;;
        --admin-pass)
            ADMIN_PASS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

if [[ -n "$DOMAIN" && -n "$ADMIN_PASS" ]]; then
    info "Auto-provisioning domain: $DOMAIN"

    REALM=$(echo "$DOMAIN" | tr '[:lower:]' '[:upper:]')
    NETBIOS=$(echo "$DOMAIN" | cut -d. -f1 | tr '[:lower:]' '[:upper:]')

    # Remove old smb.conf if exists
    rm -f /etc/samba/smb.conf

    samba-tool domain provision \
        --use-rfc2307 \
        --realm="$REALM" \
        --domain="$NETBIOS" \
        --adminpass="$ADMIN_PASS" \
        --server-role=dc \
        --dns-backend=SAMBA_INTERNAL \
        --option="dns forwarder = 8.8.8.8" \
        --adminpass="$ADMIN_PASS"

    ok "Domain provisioned: $REALM"

    # Start samba
    systemctl enable samba-ad-dc
    systemctl start samba-ad-dc
    ok "Samba AD DC service started"

    # Update .env with correct domain
    sed -i "s/DC=CORP,DC=LOCAL/DC=$NETBIOS,DC=$(echo $DOMAIN | cut -d. -f2 | tr '[:lower:]' '[:upper:]')/g" "$ENV_FILE"
    sed -i "s/ChangeMe123!/$ADMIN_PASS/g" "$ENV_FILE"
fi

# ---------------------------------------------------------------------------
# Step 7: Start the web app
# ---------------------------------------------------------------------------
info "Starting Samba 4 AD Manager..."
systemctl start samba-ad-manager

sleep 2
if systemctl is-active --quiet samba-ad-manager; then
    ok "Samba 4 AD Manager is running!"
else
    warn "Service may still be starting. Check: systemctl status samba-ad-manager"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Samba 4 AD Manager — Installation Complete!    ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Web UI:  ${BLUE}http://${SERVER_IP}:8000${NC}"
echo -e "  API:     ${BLUE}http://${SERVER_IP}:8000/docs${NC}"
echo -e "  Config:  ${APP_DIR}/.env"
echo ""

if [[ -z "$DOMAIN" ]]; then
    echo -e "  ${YELLOW}Next steps:${NC}"
    echo -e "  1. Open the Web UI in your browser"
    echo -e "  2. Complete the Setup Wizard to provision your domain"
    echo ""
fi

echo -e "  Service commands:"
echo -e "    systemctl status samba-ad-manager"
echo -e "    systemctl restart samba-ad-manager"
echo -e "    journalctl -u samba-ad-manager -f"
echo ""
