"""SPDX-License-Identifier: Apache-2.0

CDC (Consumer-Driven Contract) tests using OpenAPI/Swagger schema.

These tests verify that the API contract (OpenAPI spec generated by
FastAPI) matches what the frontend expects. If the backend changes
an endpoint, response model, or parameter, these tests break.

The OpenAPI schema at /openapi.json IS the contract.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient
from src.main import app


@pytest.fixture(scope="module")
def openapi_schema() -> dict:
    """Get the OpenAPI schema once for all tests."""
    return app.openapi()


@pytest.fixture(scope="module")
def client() -> TestClient:
    from tests.conftest import auth_token, mock_backend  # noqa: F401

    return TestClient(app)


class TestContractIAM:
    """Verify IAM API endpoints exist in OpenAPI schema."""

    @pytest.mark.unit
    def test_iam_paths_exist(self, openapi_schema: dict) -> None:
        """All expected IAM endpoints must be in the schema."""
        paths = openapi_schema.get("paths", {})
        expected = [
            "/api/v1/iam/policies",
            "/api/v1/iam/policies/{policy_path}",
            "/api/v1/iam/assignments",
            "/api/v1/iam/eval",
        ]
        for path in expected:
            assert path in paths, f"Missing IAM endpoint in OpenAPI: {path}"

    @pytest.mark.unit
    def test_iam_policy_crud_methods(self, openapi_schema: dict) -> None:
        """Policy CRUD endpoints must have correct HTTP methods."""
        paths = openapi_schema["paths"]

        assert "post" in paths["/api/v1/iam/policies"], "Missing POST /iam/policies"
        assert "get" in paths["/api/v1/iam/policies"], "Missing GET /iam/policies"

        detail = paths["/api/v1/iam/policies/{policy_path}"]
        assert "get" in detail, "Missing GET /iam/policies/{path}"
        assert "put" in detail, "Missing PUT /iam/policies/{path}"
        assert "delete" in detail, "Missing DELETE /iam/policies/{path}"

    @pytest.mark.unit
    def test_iam_assignment_methods(self, openapi_schema: dict) -> None:
        """Assignment endpoints must have GET + PUT."""
        paths = openapi_schema["paths"]
        assign = paths["/api/v1/iam/assignments"]
        assert "get" in assign, "Missing GET /iam/assignments"
        assert "put" in assign, "Missing PUT /iam/assignments"

    @pytest.mark.unit
    def test_iam_eval_method(self, openapi_schema: dict) -> None:
        """Eval endpoint must be POST."""
        paths = openapi_schema["paths"]
        assert "post" in paths["/api/v1/iam/eval"], "Missing POST /iam/eval"

    @pytest.mark.unit
    def test_policy_create_request_schema(self, openapi_schema: dict) -> None:
        """PolicyCreateRequest must have path, version, statement fields."""
        schemas = openapi_schema.get("components", {}).get("schemas", {})

        # Find PolicyCreateRequest
        assert "PolicyCreateRequest" in schemas, "Missing PolicyCreateRequest schema"
        props = schemas["PolicyCreateRequest"].get("properties", {})
        assert "path" in props, "PolicyCreateRequest missing 'path'"
        assert "version" in props, "PolicyCreateRequest missing 'version'"
        assert "statement" in props, "PolicyCreateRequest missing 'statement'"

    @pytest.mark.unit
    def test_statement_schema(self, openapi_schema: dict) -> None:
        """Statement model must have sid, effect, action, resource."""
        schemas = openapi_schema["components"]["schemas"]
        assert "Statement" in schemas, "Missing Statement schema"
        props = schemas["Statement"].get("properties", {})
        assert "effect" in props
        assert "action" in props
        assert "resource" in props

    @pytest.mark.unit
    def test_assignment_update_schema(self, openapi_schema: dict) -> None:
        """AssignmentUpdateRequest must have group/user/default fields."""
        schemas = openapi_schema["components"]["schemas"]
        assert "AssignmentUpdateRequest" in schemas
        props = schemas["AssignmentUpdateRequest"]["properties"]
        assert "group_assignments" in props
        assert "user_assignments" in props
        assert "default_policy" in props

    @pytest.mark.unit
    def test_policy_summary_response(self, openapi_schema: dict) -> None:
        """PolicySummary response must match frontend expectations."""
        schemas = openapi_schema["components"]["schemas"]
        assert "PolicySummary" in schemas
        props = schemas["PolicySummary"]["properties"]
        for field in ("path", "version", "statements", "actions", "is_system"):
            assert field in props, f"PolicySummary missing '{field}'"

    @pytest.mark.unit
    def test_audit_endpoint_exists(self, openapi_schema: dict) -> None:
        """Audit log endpoint must exist for IAM audit tab."""
        paths = openapi_schema["paths"]
        assert "/api/v1/logs/audit" in paths, "Missing /logs/audit endpoint"
        assert "get" in paths["/api/v1/logs/audit"]


class TestContractAudit:
    """Verify audit log endpoints match frontend expectations."""

    @pytest.mark.unit
    def test_audit_entry_schema(self, openapi_schema: dict) -> None:
        """AuditEntry must have all fields the frontend uses."""
        schemas = openapi_schema["components"]["schemas"]
        assert "AuditEntry" in schemas
        props = schemas["AuditEntry"]["properties"]
        required_fields = [
            "audit",
            "timestamp",
            "actor",
            "actor_ip",
            "action",
            "resource_type",
            "resource_id",
            "decision",
            "severity",
            "detail",
        ]
        for field in required_fields:
            assert field in props, f"AuditEntry missing '{field}'"

    @pytest.mark.unit
    def test_audit_pagination_schema(self, openapi_schema: dict) -> None:
        """PaginatedAudit must have items, total, page, pages."""
        schemas = openapi_schema["components"]["schemas"]
        assert "PaginatedAudit" in schemas
        props = schemas["PaginatedAudit"]["properties"]
        for field in ("items", "total", "page", "page_size", "pages"):
            assert field in props, f"PaginatedAudit missing '{field}'"


class TestContractAuth:
    """Verify auth endpoints used by IAM login flow."""

    @pytest.mark.unit
    def test_login_endpoint(self, openapi_schema: dict) -> None:
        """Login endpoint must exist."""
        paths = openapi_schema["paths"]
        assert "/api/v1/auth/login" in paths
        assert "post" in paths["/api/v1/auth/login"]

    @pytest.mark.unit
    def test_token_response_schema(self, openapi_schema: dict) -> None:
        """Login response must have access_token or mfa_required."""
        schemas = openapi_schema["components"]["schemas"]
        assert "LoginOrMfaResponse" in schemas, "Missing LoginOrMfaResponse schema"
        props = schemas["LoginOrMfaResponse"]["properties"]
        assert "access_token" in props or "mfa_required" in props
